apiVersion: v1
authProviders:
  - kind: secret
    name: public-github
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: true
  s3storage:
    bucket: aethr-gitpod-object-storage
    certificate:
      kind: secret
      name: object-storage-gitpod-token
database:
  inCluster: false
  external:
    certificate:
      kind: secret
      name: mysql-gitpod-token
domain: gitpod.aethr.cloud
imagePullSecrets: null
jaegerOperator:
  inCluster: true
kind: Full
metadata:
  region: eu-west-2
objectStorage:
  inCluster: false
  s3:
    endpoint: s3.amazonaws.com
    credentials:
      kind: secret
      name: s3-storage-token
observability:
  logLevel: info
repository: eu.gcr.io/gitpod-core-dev/build
workspace:
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
    fsShiftMethod: shiftfs
